# Copyright Rob Gage 2025

[package]
name = "pups"
version = "0.0.3"
license = "MIT"
description = "Pretty Understandable Parsers"
readme = "../README.md"
repository = "https://github.com/rob-gage/pups"
edition = "2021"

[dependencies]
pups_core = { version = "0.0.3", path = "../core" }
pups_text = { version = "0.0.3", path = "../text" }
